/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tournament = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'mode' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'roomPassword' : IDL.Text,
  'imageUrl' : IDL.Text,
  'currentPlayers' : IDL.Nat,
  'category' : IDL.Text,
  'entryFee' : IDL.Nat,
  'joinedPlayers' : IDL.Vec(IDL.Text),
  'roomId' : IDL.Text,
  'maxPlayers' : IDL.Nat,
  'prizePool' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'legendId' : IDL.Text,
  'totalMatches' : IDL.Nat,
  'createdAt' : IDL.Int,
  'wins' : IDL.Nat,
  'totalDeposited' : IDL.Nat,
});
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DepositRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : DepositStatus,
  'legendId' : IDL.Text,
  'submittedAt' : IDL.Int,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const TransactionType = IDL.Variant({
  'withdraw' : IDL.Null,
  'deposit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'date' : IDL.Int,
  'description' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const Result = IDL.Variant({
  'win' : IDL.Null,
  'draw' : IDL.Null,
  'loss' : IDL.Null,
});
export const GameMode = IDL.Variant({
  'csMod' : IDL.Null,
  'loneWolf' : IDL.Null,
  'brMod' : IDL.Null,
});
export const Match = IDL.Record({
  'result' : Result,
  'date' : IDL.Int,
  'mode' : GameMode,
  'matchId' : IDL.Text,
  'coinsWagered' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'legendId' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'jazzCashNumber' : IDL.Text,
  'gameUID' : IDL.Text,
  'isBanned' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'gameName' : IDL.Text,
  'selectedProfilePic' : IDL.Nat,
  'transactions' : IDL.Vec(Transaction),
  'totalDeposited' : IDL.Nat,
  'walletBalance' : IDL.Nat,
  'matchHistory' : IDL.Vec(Match),
});

export const idlService = IDL.Service({
  'approveDepositRequest' : IDL.Func([IDL.Text], [], []),
  'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'createTournament' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteTournament' : IDL.Func([IDL.Text], [], []),
  'getActiveTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], []),
  'getPendingDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], []),
  'getTournamentRoom' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'roomPassword' : IDL.Text, 'roomId' : IDL.Text })],
      ['query'],
    ),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getUserByLegendId' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'joinTournamentById' : IDL.Func([IDL.Text], [], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'rejectDepositRequest' : IDL.Func([IDL.Text], [], []),
  'setProfilePicture' : IDL.Func([IDL.Nat], [], []),
  'setTournamentRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitDepositRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'toggleBan' : IDL.Func([IDL.Text], [], []),
  'updatePlayerInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tournament = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'mode' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'roomPassword' : IDL.Text,
    'imageUrl' : IDL.Text,
    'currentPlayers' : IDL.Nat,
    'category' : IDL.Text,
    'entryFee' : IDL.Nat,
    'joinedPlayers' : IDL.Vec(IDL.Text),
    'roomId' : IDL.Text,
    'maxPlayers' : IDL.Nat,
    'prizePool' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'legendId' : IDL.Text,
    'totalMatches' : IDL.Nat,
    'createdAt' : IDL.Int,
    'wins' : IDL.Nat,
    'totalDeposited' : IDL.Nat,
  });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DepositRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : DepositStatus,
    'legendId' : IDL.Text,
    'submittedAt' : IDL.Int,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const TransactionType = IDL.Variant({
    'withdraw' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'date' : IDL.Int,
    'description' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const Result = IDL.Variant({
    'win' : IDL.Null,
    'draw' : IDL.Null,
    'loss' : IDL.Null,
  });
  const GameMode = IDL.Variant({
    'csMod' : IDL.Null,
    'loneWolf' : IDL.Null,
    'brMod' : IDL.Null,
  });
  const Match = IDL.Record({
    'result' : Result,
    'date' : IDL.Int,
    'mode' : GameMode,
    'matchId' : IDL.Text,
    'coinsWagered' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'legendId' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'jazzCashNumber' : IDL.Text,
    'gameUID' : IDL.Text,
    'isBanned' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'gameName' : IDL.Text,
    'selectedProfilePic' : IDL.Nat,
    'transactions' : IDL.Vec(Transaction),
    'totalDeposited' : IDL.Nat,
    'walletBalance' : IDL.Nat,
    'matchHistory' : IDL.Vec(Match),
  });
  
  return IDL.Service({
    'approveDepositRequest' : IDL.Func([IDL.Text], [], []),
    'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteTournament' : IDL.Func([IDL.Text], [], []),
    'getActiveTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], []),
    'getPendingDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], []),
    'getTournamentRoom' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'roomPassword' : IDL.Text, 'roomId' : IDL.Text })],
        ['query'],
      ),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getUserByLegendId' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'joinTournamentById' : IDL.Func([IDL.Text], [], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'rejectDepositRequest' : IDL.Func([IDL.Text], [], []),
    'setProfilePicture' : IDL.Func([IDL.Nat], [], []),
    'setTournamentRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitDepositRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'toggleBan' : IDL.Func([IDL.Text], [], []),
    'updatePlayerInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };