/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DepositRequest {
  'id' : string,
  'status' : DepositStatus,
  'legendId' : string,
  'submittedAt' : bigint,
  'amount' : bigint,
  'transactionId' : string,
}
export type DepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type GameMode = { 'csMod' : null } |
  { 'loneWolf' : null } |
  { 'brMod' : null };
export interface LeaderboardEntry {
  'legendId' : string,
  'totalMatches' : bigint,
  'createdAt' : bigint,
  'wins' : bigint,
  'totalProfit' : bigint,
  'totalDeposited' : bigint,
}
export interface Match {
  'result' : Result,
  'date' : bigint,
  'mode' : GameMode,
  'matchId' : string,
  'coinsWagered' : bigint,
}
export type Result = { 'win' : null } |
  { 'draw' : null } |
  { 'loss' : null };
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface Tournament {
  'id' : string,
  'title' : string,
  'mode' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'roomPassword' : string,
  'imageUrl' : string,
  'returningCoins' : bigint,
  'currentPlayers' : bigint,
  'category' : string,
  'entryFee' : bigint,
  'joinedPlayers' : Array<string>,
  'roomId' : string,
  'maxPlayers' : bigint,
  'prizePool' : string,
}
export interface Transaction {
  'date' : bigint,
  'description' : string,
  'txType' : TransactionType,
  'amount' : bigint,
}
export type TransactionType = { 'withdraw' : null } |
  { 'deposit' : null };
export interface UserProfile {
  'legendId' : string,
  'createdAt' : bigint,
  'role' : Role,
  'jazzCashNumber' : string,
  'totalProfit' : bigint,
  'gameUID' : string,
  'isBanned' : boolean,
  'passwordHash' : string,
  'gameName' : string,
  'selectedProfilePic' : bigint,
  'transactions' : Array<Transaction>,
  'totalDeposited' : bigint,
  'walletBalance' : bigint,
  'matchHistory' : Array<Match>,
}
export interface _SERVICE {
  'approveDepositRequest' : ActorMethod<[string], undefined>,
  'authenticate' : ActorMethod<[string, string], boolean>,
  'createTournament' : ActorMethod<
    [string, string, string, bigint, string, bigint, string, bigint],
    string
  >,
  'declareMatchResult' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'deleteTournament' : ActorMethod<[string], undefined>,
  'getActiveTournaments' : ActorMethod<[], Array<Tournament>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getPendingDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getTournamentRoom' : ActorMethod<
    [string, string],
    { 'roomPassword' : string, 'roomId' : string }
  >,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'getUserByLegendId' : ActorMethod<[string], UserProfile>,
  'joinTournamentById' : ActorMethod<[string], undefined>,
  'register' : ActorMethod<[string, string, string, string], string>,
  'rejectDepositRequest' : ActorMethod<[string], undefined>,
  'setProfilePicture' : ActorMethod<[bigint], undefined>,
  'setTournamentRoom' : ActorMethod<[string, string, string], undefined>,
  'submitDepositRequest' : ActorMethod<[bigint, string], undefined>,
  'toggleBan' : ActorMethod<[string], undefined>,
  'updatePlayerInfo' : ActorMethod<[string, string, string], undefined>,
  'updateTournament' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      boolean,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];