/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomShopAvatar {
  'src' : string,
  'expiryDate' : bigint,
  'name' : string,
  'discount' : bigint,
  'index' : bigint,
  'price' : bigint,
}
export interface DepositRequest {
  'id' : string,
  'status' : DepositStatus,
  'legendId' : string,
  'submittedAt' : bigint,
  'amount' : bigint,
  'transactionId' : string,
}
export type DepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type GameMode = { 'csMod' : null } |
  { 'loneWolf' : null } |
  { 'brMod' : null };
export interface LeaderboardEntry {
  'legendId' : string,
  'totalMatches' : bigint,
  'purchasedShopAvatars' : Array<bigint>,
  'createdAt' : bigint,
  'purchasedFrames' : Array<bigint>,
  'wins' : bigint,
  'totalProfit' : bigint,
  'gameName' : string,
  'selectedProfilePic' : bigint,
  'totalDeposited' : bigint,
  'selectedFrame' : bigint,
}
export interface Match {
  'result' : Result,
  'date' : bigint,
  'mode' : GameMode,
  'matchId' : string,
  'coinsWagered' : bigint,
}
export type Result = { 'win' : null } |
  { 'draw' : null } |
  { 'loss' : null };
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface ShopFrame {
  'src' : string,
  'expiryDate' : bigint,
  'name' : string,
  'discount' : bigint,
  'index' : bigint,
  'price' : bigint,
}
export interface Tournament {
  'id' : string,
  'title' : string,
  'mode' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'roomPassword' : string,
  'imageUrl' : string,
  'returningCoins' : bigint,
  'currentPlayers' : bigint,
  'category' : string,
  'entryFee' : bigint,
  'joinedPlayers' : Array<string>,
  'roomId' : string,
  'maxPlayers' : bigint,
  'prizePool' : string,
}
export interface Transaction {
  'date' : bigint,
  'description' : string,
  'txType' : TransactionType,
  'amount' : bigint,
}
export type TransactionType = { 'withdraw' : null } |
  { 'deposit' : null };
export interface UserProfile {
  'legendId' : string,
  'purchasedShopAvatars' : Array<bigint>,
  'createdAt' : bigint,
  'role' : Role,
  'purchasedFrames' : Array<bigint>,
  'hasClaimedRouletteReward' : boolean,
  'jazzCashNumber' : string,
  'totalProfit' : bigint,
  'gameUID' : string,
  'isBanned' : boolean,
  'passwordHash' : string,
  'gameName' : string,
  'selectedProfilePic' : bigint,
  'transactions' : Array<Transaction>,
  'totalDeposited' : bigint,
  'walletBalance' : bigint,
  'matchHistory' : Array<Match>,
  'selectedFrame' : bigint,
}
export interface WithdrawRequest {
  'id' : string,
  'jazzCashName' : string,
  'status' : WithdrawStatus,
  'paymentMethod' : string,
  'legendId' : string,
  'submittedAt' : bigint,
  'jazzCashNumber' : string,
  'amount' : bigint,
}
export type WithdrawStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  'addCoins' : ActorMethod<[string, string, string, bigint], undefined>,
  'addCustomShopAvatar' : ActorMethod<
    [string, string, string, bigint, bigint, bigint, string],
    bigint
  >,
  'addShopFrame' : ActorMethod<
    [string, string, string, bigint, bigint, bigint, string],
    bigint
  >,
  'adminAdjustRanking' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'approveDepositRequest' : ActorMethod<[string, string, string], undefined>,
  'approveWithdrawRequest' : ActorMethod<[string, string, string], undefined>,
  'authenticate' : ActorMethod<[string, string], boolean>,
  'buyCustomShopAvatar' : ActorMethod<[string, string, bigint], undefined>,
  'buyShopAvatar' : ActorMethod<[string, string, bigint], undefined>,
  'buyShopFrame' : ActorMethod<[string, string, bigint], undefined>,
  'claimRouletteReward' : ActorMethod<[string, string, bigint], undefined>,
  'createTournament' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      bigint,
    ],
    string
  >,
  'declareMatchResult' : ActorMethod<
    [string, string, string, string, string, bigint, bigint],
    undefined
  >,
  'deleteCustomShopAvatar' : ActorMethod<[string, string, bigint], undefined>,
  'deleteShopFrame' : ActorMethod<[string, string, bigint], undefined>,
  'deleteTournament' : ActorMethod<[string, string, string], undefined>,
  'deleteUser' : ActorMethod<[string, string, string], undefined>,
  'getActiveTournaments' : ActorMethod<[], Array<Tournament>>,
  'getAllUsers' : ActorMethod<[string], Array<UserProfile>>,
  'getCustomShopAvatars' : ActorMethod<[], Array<CustomShopAvatar>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyDepositRequests' : ActorMethod<[string, string], Array<DepositRequest>>,
  'getNextLegendId' : ActorMethod<[], string>,
  'getPendingDepositRequests' : ActorMethod<
    [string, string],
    Array<DepositRequest>
  >,
  'getPendingWithdrawRequests' : ActorMethod<
    [string, string],
    Array<WithdrawRequest>
  >,
  'getShopFrames' : ActorMethod<[], Array<ShopFrame>>,
  'getTournamentRoom' : ActorMethod<
    [string, string],
    { 'roomPassword' : string, 'roomId' : string }
  >,
  'getTournaments' : ActorMethod<[string], Array<Tournament>>,
  'getUserByLegendId' : ActorMethod<[string], UserProfile>,
  'getUserHasClaimedRoulette' : ActorMethod<[string], boolean>,
  'joinTournamentById' : ActorMethod<[string, string, string], undefined>,
  'register' : ActorMethod<[string, string, string, string], string>,
  'rejectDepositRequest' : ActorMethod<[string, string, string], undefined>,
  'rejectWithdrawRequest' : ActorMethod<[string, string, string], undefined>,
  'resetUsersWithDepositTierAvatar' : ActorMethod<
    [string, string, bigint],
    undefined
  >,
  'setProfileFrame' : ActorMethod<[string, string, bigint], undefined>,
  'setProfilePicture' : ActorMethod<[string, string, bigint], undefined>,
  'setTournamentRoom' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitDepositRequest' : ActorMethod<
    [string, string, bigint, string],
    undefined
  >,
  'submitWithdrawRequest' : ActorMethod<
    [string, string, bigint, string, string, string],
    undefined
  >,
  'toggleBan' : ActorMethod<[string, string, string], undefined>,
  'updateCustomShopAvatar' : ActorMethod<
    [string, string, bigint, string, bigint, bigint, bigint],
    undefined
  >,
  'updatePlayerInfo' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateShopFrame' : ActorMethod<
    [string, string, bigint, string, bigint, bigint, bigint],
    undefined
  >,
  'updateTournament' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      boolean,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];