/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tournament = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'mode' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'roomPassword' : IDL.Text,
  'imageUrl' : IDL.Text,
  'returningCoins' : IDL.Nat,
  'currentPlayers' : IDL.Nat,
  'category' : IDL.Text,
  'entryFee' : IDL.Nat,
  'joinedPlayers' : IDL.Vec(IDL.Text),
  'roomId' : IDL.Text,
  'maxPlayers' : IDL.Nat,
  'prizePool' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const TransactionType = IDL.Variant({
  'withdraw' : IDL.Null,
  'deposit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'date' : IDL.Int,
  'description' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const Result = IDL.Variant({
  'win' : IDL.Null,
  'draw' : IDL.Null,
  'loss' : IDL.Null,
});
export const GameMode = IDL.Variant({
  'csMod' : IDL.Null,
  'loneWolf' : IDL.Null,
  'brMod' : IDL.Null,
});
export const Match = IDL.Record({
  'result' : Result,
  'date' : IDL.Int,
  'mode' : GameMode,
  'matchId' : IDL.Text,
  'coinsWagered' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'legendId' : IDL.Text,
  'purchasedShopAvatars' : IDL.Vec(IDL.Nat),
  'createdAt' : IDL.Int,
  'role' : Role,
  'purchasedFrames' : IDL.Vec(IDL.Nat),
  'hasClaimedRouletteReward' : IDL.Bool,
  'jazzCashNumber' : IDL.Text,
  'totalProfit' : IDL.Nat,
  'gameUID' : IDL.Text,
  'isBanned' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'gameName' : IDL.Text,
  'selectedProfilePic' : IDL.Nat,
  'transactions' : IDL.Vec(Transaction),
  'totalDeposited' : IDL.Nat,
  'walletBalance' : IDL.Nat,
  'matchHistory' : IDL.Vec(Match),
  'selectedFrame' : IDL.Nat,
});
export const CustomShopAvatar = IDL.Record({
  'src' : IDL.Text,
  'expiryDate' : IDL.Int,
  'name' : IDL.Text,
  'discount' : IDL.Nat,
  'index' : IDL.Nat,
  'price' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'legendId' : IDL.Text,
  'totalMatches' : IDL.Nat,
  'purchasedShopAvatars' : IDL.Vec(IDL.Nat),
  'createdAt' : IDL.Int,
  'purchasedFrames' : IDL.Vec(IDL.Nat),
  'wins' : IDL.Nat,
  'totalProfit' : IDL.Nat,
  'gameName' : IDL.Text,
  'selectedProfilePic' : IDL.Nat,
  'totalDeposited' : IDL.Nat,
  'selectedFrame' : IDL.Nat,
});
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DepositRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : DepositStatus,
  'legendId' : IDL.Text,
  'submittedAt' : IDL.Int,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const WithdrawStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawRequest = IDL.Record({
  'id' : IDL.Text,
  'jazzCashName' : IDL.Text,
  'status' : WithdrawStatus,
  'paymentMethod' : IDL.Text,
  'legendId' : IDL.Text,
  'submittedAt' : IDL.Int,
  'jazzCashNumber' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ShopFrame = IDL.Record({
  'src' : IDL.Text,
  'expiryDate' : IDL.Int,
  'name' : IDL.Text,
  'discount' : IDL.Nat,
  'index' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCoins' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addCustomShopAvatar' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addShopFrame' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adminAdjustRanking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'approveDepositRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'approveWithdrawRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'buyCustomShopAvatar' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'buyShopAvatar' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'buyShopFrame' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'claimRouletteReward' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'declareMatchResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'deleteCustomShopAvatar' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteShopFrame' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteTournament' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getActiveTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'getCustomShopAvatars' : IDL.Func([], [IDL.Vec(CustomShopAvatar)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyDepositRequests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DepositRequest)],
      [],
    ),
  'getNextLegendId' : IDL.Func([], [IDL.Text], ['query']),
  'getPendingDepositRequests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DepositRequest)],
      [],
    ),
  'getPendingWithdrawRequests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(WithdrawRequest)],
      [],
    ),
  'getShopFrames' : IDL.Func([], [IDL.Vec(ShopFrame)], ['query']),
  'getTournamentRoom' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'roomPassword' : IDL.Text, 'roomId' : IDL.Text })],
      ['query'],
    ),
  'getTournaments' : IDL.Func([IDL.Text], [IDL.Vec(Tournament)], ['query']),
  'getUserByLegendId' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'getUserHasClaimedRoulette' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinTournamentById' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'rejectDepositRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectWithdrawRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'resetUsersWithDepositTierAvatar' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'setProfileFrame' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'setProfilePicture' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'setTournamentRoom' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitDepositRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'submitWithdrawRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'toggleBan' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateCustomShopAvatar' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int],
      [],
      [],
    ),
  'updatePlayerInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateShopFrame' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int],
      [],
      [],
    ),
  'updateTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tournament = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'mode' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'roomPassword' : IDL.Text,
    'imageUrl' : IDL.Text,
    'returningCoins' : IDL.Nat,
    'currentPlayers' : IDL.Nat,
    'category' : IDL.Text,
    'entryFee' : IDL.Nat,
    'joinedPlayers' : IDL.Vec(IDL.Text),
    'roomId' : IDL.Text,
    'maxPlayers' : IDL.Nat,
    'prizePool' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const TransactionType = IDL.Variant({
    'withdraw' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'date' : IDL.Int,
    'description' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const Result = IDL.Variant({
    'win' : IDL.Null,
    'draw' : IDL.Null,
    'loss' : IDL.Null,
  });
  const GameMode = IDL.Variant({
    'csMod' : IDL.Null,
    'loneWolf' : IDL.Null,
    'brMod' : IDL.Null,
  });
  const Match = IDL.Record({
    'result' : Result,
    'date' : IDL.Int,
    'mode' : GameMode,
    'matchId' : IDL.Text,
    'coinsWagered' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'legendId' : IDL.Text,
    'purchasedShopAvatars' : IDL.Vec(IDL.Nat),
    'createdAt' : IDL.Int,
    'role' : Role,
    'purchasedFrames' : IDL.Vec(IDL.Nat),
    'hasClaimedRouletteReward' : IDL.Bool,
    'jazzCashNumber' : IDL.Text,
    'totalProfit' : IDL.Nat,
    'gameUID' : IDL.Text,
    'isBanned' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'gameName' : IDL.Text,
    'selectedProfilePic' : IDL.Nat,
    'transactions' : IDL.Vec(Transaction),
    'totalDeposited' : IDL.Nat,
    'walletBalance' : IDL.Nat,
    'matchHistory' : IDL.Vec(Match),
    'selectedFrame' : IDL.Nat,
  });
  const CustomShopAvatar = IDL.Record({
    'src' : IDL.Text,
    'expiryDate' : IDL.Int,
    'name' : IDL.Text,
    'discount' : IDL.Nat,
    'index' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'legendId' : IDL.Text,
    'totalMatches' : IDL.Nat,
    'purchasedShopAvatars' : IDL.Vec(IDL.Nat),
    'createdAt' : IDL.Int,
    'purchasedFrames' : IDL.Vec(IDL.Nat),
    'wins' : IDL.Nat,
    'totalProfit' : IDL.Nat,
    'gameName' : IDL.Text,
    'selectedProfilePic' : IDL.Nat,
    'totalDeposited' : IDL.Nat,
    'selectedFrame' : IDL.Nat,
  });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DepositRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : DepositStatus,
    'legendId' : IDL.Text,
    'submittedAt' : IDL.Int,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const WithdrawStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawRequest = IDL.Record({
    'id' : IDL.Text,
    'jazzCashName' : IDL.Text,
    'status' : WithdrawStatus,
    'paymentMethod' : IDL.Text,
    'legendId' : IDL.Text,
    'submittedAt' : IDL.Int,
    'jazzCashNumber' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ShopFrame = IDL.Record({
    'src' : IDL.Text,
    'expiryDate' : IDL.Int,
    'name' : IDL.Text,
    'discount' : IDL.Nat,
    'index' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCoins' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addCustomShopAvatar' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addShopFrame' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminAdjustRanking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'approveDepositRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'approveWithdrawRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'buyCustomShopAvatar' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'buyShopAvatar' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'buyShopFrame' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'claimRouletteReward' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'declareMatchResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'deleteCustomShopAvatar' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'deleteShopFrame' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'deleteTournament' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getActiveTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'getCustomShopAvatars' : IDL.Func(
        [],
        [IDL.Vec(CustomShopAvatar)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyDepositRequests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DepositRequest)],
        [],
      ),
    'getNextLegendId' : IDL.Func([], [IDL.Text], ['query']),
    'getPendingDepositRequests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DepositRequest)],
        [],
      ),
    'getPendingWithdrawRequests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(WithdrawRequest)],
        [],
      ),
    'getShopFrames' : IDL.Func([], [IDL.Vec(ShopFrame)], ['query']),
    'getTournamentRoom' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'roomPassword' : IDL.Text, 'roomId' : IDL.Text })],
        ['query'],
      ),
    'getTournaments' : IDL.Func([IDL.Text], [IDL.Vec(Tournament)], ['query']),
    'getUserByLegendId' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'getUserHasClaimedRoulette' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinTournamentById' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'rejectDepositRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectWithdrawRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'resetUsersWithDepositTierAvatar' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'setProfileFrame' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'setProfilePicture' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'setTournamentRoom' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitDepositRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'submitWithdrawRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'toggleBan' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateCustomShopAvatar' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int],
        [],
        [],
      ),
    'updatePlayerInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateShopFrame' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int],
        [],
        [],
      ),
    'updateTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };