/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DepositRequest {
  'id' : string,
  'status' : DepositStatus,
  'legendId' : string,
  'submittedAt' : bigint,
  'amount' : bigint,
  'transactionId' : string,
}
export type DepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type GameMode = { 'csMod' : null } |
  { 'loneWolf' : null } |
  { 'brMod' : null };
export interface Match {
  'result' : Result,
  'date' : bigint,
  'mode' : GameMode,
  'matchId' : string,
  'coinsWagered' : bigint,
}
export type Result = { 'win' : null } |
  { 'draw' : null } |
  { 'loss' : null };
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface Transaction {
  'date' : bigint,
  'description' : string,
  'txType' : TransactionType,
  'amount' : bigint,
}
export type TransactionType = { 'withdraw' : null } |
  { 'deposit' : null };
export interface UserProfile {
  'legendId' : string,
  'createdAt' : bigint,
  'role' : Role,
  'isBanned' : boolean,
  'passwordHash' : string,
  'transactions' : Array<Transaction>,
  'walletBalance' : bigint,
  'matchHistory' : Array<Match>,
}
export interface _SERVICE {
  'approveDepositRequest' : ActorMethod<[string], undefined>,
  'authenticate' : ActorMethod<[string, string], boolean>,
  'getMyDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getPendingDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getUserByLegendId' : ActorMethod<[string], UserProfile>,
  'joinTournament' : ActorMethod<[GameMode, bigint], undefined>,
  'register' : ActorMethod<[string, string], undefined>,
  'rejectDepositRequest' : ActorMethod<[string], undefined>,
  'submitDepositRequest' : ActorMethod<[bigint, string], undefined>,
  'toggleBan' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];