/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const TransactionType = IDL.Variant({
  'withdraw' : IDL.Null,
  'deposit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'date' : IDL.Int,
  'description' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const Result = IDL.Variant({
  'win' : IDL.Null,
  'draw' : IDL.Null,
  'loss' : IDL.Null,
});
export const GameMode = IDL.Variant({
  'csMod' : IDL.Null,
  'loneWolf' : IDL.Null,
  'brMod' : IDL.Null,
});
export const Match = IDL.Record({
  'result' : Result,
  'date' : IDL.Int,
  'mode' : GameMode,
  'matchId' : IDL.Text,
  'coinsWagered' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'legendId' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'isBanned' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'transactions' : IDL.Vec(Transaction),
  'walletBalance' : IDL.Nat,
  'matchHistory' : IDL.Vec(Match),
});

export const idlService = IDL.Service({
  'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getUserByLegendId' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'joinTournament' : IDL.Func([GameMode, IDL.Nat], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleBan' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const TransactionType = IDL.Variant({
    'withdraw' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'date' : IDL.Int,
    'description' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const Result = IDL.Variant({
    'win' : IDL.Null,
    'draw' : IDL.Null,
    'loss' : IDL.Null,
  });
  const GameMode = IDL.Variant({
    'csMod' : IDL.Null,
    'loneWolf' : IDL.Null,
    'brMod' : IDL.Null,
  });
  const Match = IDL.Record({
    'result' : Result,
    'date' : IDL.Int,
    'mode' : GameMode,
    'matchId' : IDL.Text,
    'coinsWagered' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'legendId' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'isBanned' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'transactions' : IDL.Vec(Transaction),
    'walletBalance' : IDL.Nat,
    'matchHistory' : IDL.Vec(Match),
  });
  
  return IDL.Service({
    'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getUserByLegendId' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'joinTournament' : IDL.Func([GameMode, IDL.Nat], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleBan' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };