/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Transaction {
    date: bigint;
    description: string;
    txType: TransactionType;
    amount: bigint;
}
export interface LeaderboardEntry {
    legendId: string;
    totalMatches: bigint;
    createdAt: bigint;
    wins: bigint;
    totalDeposited: bigint;
}
export interface DepositRequest {
    id: string;
    status: DepositStatus;
    legendId: string;
    submittedAt: bigint;
    amount: bigint;
    transactionId: string;
}
export interface Tournament {
    id: string;
    title: string;
    mode: string;
    createdAt: bigint;
    isActive: boolean;
    roomPassword: string;
    imageUrl: string;
    currentPlayers: bigint;
    category: string;
    entryFee: bigint;
    joinedPlayers: Array<string>;
    roomId: string;
    maxPlayers: bigint;
    prizePool: string;
}
export interface Match {
    result: Result;
    date: bigint;
    mode: GameMode;
    matchId: string;
    coinsWagered: bigint;
}
export interface UserProfile {
    legendId: string;
    createdAt: bigint;
    role: Role;
    jazzCashNumber: string;
    gameUID: string;
    isBanned: boolean;
    passwordHash: string;
    gameName: string;
    selectedProfilePic: bigint;
    transactions: Array<Transaction>;
    totalDeposited: bigint;
    walletBalance: bigint;
    matchHistory: Array<Match>;
}
export enum DepositStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum GameMode {
    csMod = "csMod",
    loneWolf = "loneWolf",
    brMod = "brMod"
}
export enum Result {
    win = "win",
    draw = "draw",
    loss = "loss"
}
export enum Role {
    admin = "admin",
    user = "user"
}
export enum TransactionType {
    withdraw = "withdraw",
    deposit = "deposit"
}
export interface backendInterface {
    approveDepositRequest(requestId: string): Promise<void>;
    authenticate(legendId: string, passwordHash: string): Promise<boolean>;
    createTournament(title: string, category: string, mode: string, entryFee: bigint, prizePool: string, maxPlayers: bigint, imageUrl: string): Promise<string>;
    deleteTournament(id: string): Promise<void>;
    getActiveTournaments(): Promise<Array<Tournament>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMyDepositRequests(): Promise<Array<DepositRequest>>;
    getPendingDepositRequests(): Promise<Array<DepositRequest>>;
    getTournamentRoom(tournamentId: string, legendId: string): Promise<{
        roomPassword: string;
        roomId: string;
    }>;
    getTournaments(): Promise<Array<Tournament>>;
    getUserByLegendId(legendId: string): Promise<UserProfile>;
    joinTournamentById(tournamentId: string): Promise<void>;
    register(legendId: string, passwordHash: string, jazzCash: string, uid: string, ignName: string): Promise<void>;
    rejectDepositRequest(requestId: string): Promise<void>;
    setProfilePicture(picIndex: bigint): Promise<void>;
    setTournamentRoom(tournamentId: string, roomId: string, roomPassword: string): Promise<void>;
    submitDepositRequest(amount: bigint, transactionId: string): Promise<void>;
    toggleBan(legendId: string): Promise<void>;
    updatePlayerInfo(gameName: string, gameUID: string, jazzCashNumber: string): Promise<void>;
    updateTournament(id: string, title: string, category: string, mode: string, entryFee: bigint, prizePool: string, maxPlayers: bigint, imageUrl: string, isActive: boolean): Promise<void>;
}
import type { DepositRequest as _DepositRequest, DepositStatus as _DepositStatus, GameMode as _GameMode, Match as _Match, Result as _Result, Role as _Role, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveDepositRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDepositRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDepositRequest(arg0);
            return result;
        }
    }
    async authenticate(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticate(arg0, arg1);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteTournament(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTournament(arg0);
            return result;
        }
    }
    async getActiveTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTournaments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTournaments();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDepositRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDepositRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDepositRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDepositRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentRoom(arg0: string, arg1: string): Promise<{
        roomPassword: string;
        roomId: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentRoom(arg0, arg1);
            return result;
        }
    }
    async getTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournaments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournaments();
            return result;
        }
    }
    async getUserByLegendId(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByLegendId(arg0);
                return from_candid_UserProfile_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByLegendId(arg0);
            return from_candid_UserProfile_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinTournamentById(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTournamentById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTournamentById(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async rejectDepositRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDepositRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDepositRequest(arg0);
            return result;
        }
    }
    async setProfilePicture(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfilePicture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfilePicture(arg0);
            return result;
        }
    }
    async setTournamentRoom(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTournamentRoom(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTournamentRoom(arg0, arg1, arg2);
            return result;
        }
    }
    async submitDepositRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDepositRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDepositRequest(arg0, arg1);
            return result;
        }
    }
    async toggleBan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBan(arg0);
            return result;
        }
    }
    async updatePlayerInfo(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerInfo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerInfo(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTournament(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: bigint, arg7: string, arg8: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
}
function from_candid_DepositRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositRequest): DepositRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_DepositStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositStatus): DepositStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_GameMode_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: bigint;
    description: string;
    txType: _TransactionType;
    amount: bigint;
}): {
    date: bigint;
    description: string;
    txType: TransactionType;
    amount: bigint;
} {
    return {
        date: value.date,
        description: value.description,
        txType: from_candid_TransactionType_n13(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: _Result;
    date: bigint;
    mode: _GameMode;
    matchId: string;
    coinsWagered: bigint;
}): {
    result: Result;
    date: bigint;
    mode: GameMode;
    matchId: string;
    coinsWagered: bigint;
} {
    return {
        result: from_candid_Result_n18(_uploadFile, _downloadFile, value.result),
        date: value.date,
        mode: from_candid_GameMode_n20(_uploadFile, _downloadFile, value.mode),
        matchId: value.matchId,
        coinsWagered: value.coinsWagered
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _DepositStatus;
    legendId: string;
    submittedAt: bigint;
    amount: bigint;
    transactionId: string;
}): {
    id: string;
    status: DepositStatus;
    legendId: string;
    submittedAt: bigint;
    amount: bigint;
    transactionId: string;
} {
    return {
        id: value.id,
        status: from_candid_DepositStatus_n4(_uploadFile, _downloadFile, value.status),
        legendId: value.legendId,
        submittedAt: value.submittedAt,
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    legendId: string;
    createdAt: bigint;
    role: _Role;
    jazzCashNumber: string;
    gameUID: string;
    isBanned: boolean;
    passwordHash: string;
    gameName: string;
    selectedProfilePic: bigint;
    transactions: Array<_Transaction>;
    totalDeposited: bigint;
    walletBalance: bigint;
    matchHistory: Array<_Match>;
}): {
    legendId: string;
    createdAt: bigint;
    role: Role;
    jazzCashNumber: string;
    gameUID: string;
    isBanned: boolean;
    passwordHash: string;
    gameName: string;
    selectedProfilePic: bigint;
    transactions: Array<Transaction>;
    totalDeposited: bigint;
    walletBalance: bigint;
    matchHistory: Array<Match>;
} {
    return {
        legendId: value.legendId,
        createdAt: value.createdAt,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role),
        jazzCashNumber: value.jazzCashNumber,
        gameUID: value.gameUID,
        isBanned: value.isBanned,
        passwordHash: value.passwordHash,
        gameName: value.gameName,
        selectedProfilePic: value.selectedProfilePic,
        transactions: from_candid_vec_n10(_uploadFile, _downloadFile, value.transactions),
        totalDeposited: value.totalDeposited,
        walletBalance: value.walletBalance,
        matchHistory: from_candid_vec_n15(_uploadFile, _downloadFile, value.matchHistory)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdraw: null;
} | {
    deposit: null;
}): TransactionType {
    return "withdraw" in value ? TransactionType.withdraw : "deposit" in value ? TransactionType.deposit : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    win: null;
} | {
    draw: null;
} | {
    loss: null;
}): Result {
    return "win" in value ? Result.win : "draw" in value ? Result.draw : "loss" in value ? Result.loss : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    csMod: null;
} | {
    loneWolf: null;
} | {
    brMod: null;
}): GameMode {
    return "csMod" in value ? GameMode.csMod : "loneWolf" in value ? GameMode.loneWolf : "brMod" in value ? GameMode.brMod : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): DepositStatus {
    return "pending" in value ? DepositStatus.pending : "approved" in value ? DepositStatus.approved : "rejected" in value ? DepositStatus.rejected : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositRequest>): Array<DepositRequest> {
    return value.map((x)=>from_candid_DepositRequest_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
